Update vm

diff --git a/vm b/vm
--- a/vm
+++ b/vm
@@ -58,8 +58,8 @@ else
 echo "windows2022.raw >= 46G, no resize needed."
 fi
 echo "Downloading OVMF.fd from Clear Linux..."
-curl -L -o OVMF.fd https://github.com/clearlinux/common/raw/refs/heads/master/OVMF.fd || { echo "Failed to download OVMF.fd"; exit 1; }
-chmod 644 ./OVMF.fd
+curl -L -o /home/user/myapp/vm/OVMF.fd https://github.com/clearlinux/common/raw/refs/heads/master/OVMF.fd || { echo "Failed to download OVMF.fd"; exit 1; }
+chmod 644 /home/user/myapp/vm/OVMF.fd
 echo "user: administrator" > /home/user/myapp/readme.txt
 echo "pass: Datnguyentv.com" >> /home/user/myapp/readme.txt
 echo "script by fb.com/thoai.ngoxuan" >> /home/user/myapp/readme.txt
